// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package wire

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// CreateAuctionJSONBody defines parameters for CreateAuction.
type CreateAuctionJSONBody struct {
	// DurationSeconds Duration of the auction in seconds (1 min to 7 days)
	DurationSeconds int                `json:"duration_seconds"`
	ItemId          openapi_types.UUID `json:"item_id"`

	// StartPrice Starting bid price in copper coins
	StartPrice int `json:"start_price"`
}

// PlaceBidJSONBody defines parameters for PlaceBid.
type PlaceBidJSONBody struct {
	// Amount New bid amount in copper coins
	Amount int `json:"amount"`
}

// CreateListingJSONBody defines parameters for CreateListing.
type CreateListingJSONBody struct {
	ItemId openapi_types.UUID `json:"item_id"`

	// Price Fixed price in copper coins
	Price int `json:"price"`
}

// DepositFundsJSONBody defines parameters for DepositFunds.
type DepositFundsJSONBody struct {
	// Amount The amount to deposit in copper coins (smallest currency unit)
	Amount int `json:"amount"`
}

// CreateAuctionJSONRequestBody defines body for CreateAuction for application/json ContentType.
type CreateAuctionJSONRequestBody CreateAuctionJSONBody

// PlaceBidJSONRequestBody defines body for PlaceBid for application/json ContentType.
type PlaceBidJSONRequestBody PlaceBidJSONBody

// CreateListingJSONRequestBody defines body for CreateListing for application/json ContentType.
type CreateListingJSONRequestBody CreateListingJSONBody

// DepositFundsJSONRequestBody defines body for DepositFunds for application/json ContentType.
type DepositFundsJSONRequestBody DepositFundsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List active auctions (Legendary items only)
	// (GET /auctions)
	ListAuctions(ctx echo.Context) error
	// List a Legendary item for auction
	// (POST /auctions)
	CreateAuction(ctx echo.Context) error
	// Place a bid on an active auction
	// (POST /auctions/{id}/bids)
	PlaceBid(ctx echo.Context, id openapi_types.UUID) error
	// List authenticated user's inventory
	// (GET /inventory)
	ListInventory(ctx echo.Context) error
	// List active marketplace listings (Common & Rare items)
	// (GET /marketplace/listings)
	ListListings(ctx echo.Context) error
	// Create a fixed-price listing
	// (POST /marketplace/listings)
	CreateListing(ctx echo.Context) error
	// Buy a listed item instantly
	// (POST /marketplace/listings/{id}/buy)
	BuyListing(ctx echo.Context, id openapi_types.UUID) error
	// Get wallet balance
	// (GET /wallet)
	GetWallet(ctx echo.Context) error
	// Deposit funds into wallet
	// (POST /wallet)
	DepositFunds(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListAuctions converts echo context to params.
func (w *ServerInterfaceWrapper) ListAuctions(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListAuctions(ctx)
	return err
}

// CreateAuction converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAuction(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAuction(ctx)
	return err
}

// PlaceBid converts echo context to params.
func (w *ServerInterfaceWrapper) PlaceBid(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PlaceBid(ctx, id)
	return err
}

// ListInventory converts echo context to params.
func (w *ServerInterfaceWrapper) ListInventory(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInventory(ctx)
	return err
}

// ListListings converts echo context to params.
func (w *ServerInterfaceWrapper) ListListings(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListListings(ctx)
	return err
}

// CreateListing converts echo context to params.
func (w *ServerInterfaceWrapper) CreateListing(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateListing(ctx)
	return err
}

// BuyListing converts echo context to params.
func (w *ServerInterfaceWrapper) BuyListing(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BuyListing(ctx, id)
	return err
}

// GetWallet converts echo context to params.
func (w *ServerInterfaceWrapper) GetWallet(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWallet(ctx)
	return err
}

// DepositFunds converts echo context to params.
func (w *ServerInterfaceWrapper) DepositFunds(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DepositFunds(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/auctions", wrapper.ListAuctions)
	router.POST(baseURL+"/auctions", wrapper.CreateAuction)
	router.POST(baseURL+"/auctions/:id/bids", wrapper.PlaceBid)
	router.GET(baseURL+"/inventory", wrapper.ListInventory)
	router.GET(baseURL+"/marketplace/listings", wrapper.ListListings)
	router.POST(baseURL+"/marketplace/listings", wrapper.CreateListing)
	router.POST(baseURL+"/marketplace/listings/:id/buy", wrapper.BuyListing)
	router.GET(baseURL+"/wallet", wrapper.GetWallet)
	router.POST(baseURL+"/wallet", wrapper.DepositFunds)

}
