// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package wire

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for ListAuctions200JSONResponseBodyItemRarity.
const (
	ListAuctions200JSONResponseBodyItemRarityCOMMON    ListAuctions200JSONResponseBodyItemRarity = "COMMON"
	ListAuctions200JSONResponseBodyItemRarityLEGENDARY ListAuctions200JSONResponseBodyItemRarity = "LEGENDARY"
	ListAuctions200JSONResponseBodyItemRarityRARE      ListAuctions200JSONResponseBodyItemRarity = "RARE"
)

// Valid indicates whether the value is a known member of the ListAuctions200JSONResponseBodyItemRarity enum.
func (e ListAuctions200JSONResponseBodyItemRarity) Valid() bool {
	switch e {
	case ListAuctions200JSONResponseBodyItemRarityCOMMON:
		return true
	case ListAuctions200JSONResponseBodyItemRarityLEGENDARY:
		return true
	case ListAuctions200JSONResponseBodyItemRarityRARE:
		return true
	default:
		return false
	}
}

// Defines values for ListAuctions200JSONResponseBodyStatus.
const (
	ListAuctions200JSONResponseBodyStatusACTIVE    ListAuctions200JSONResponseBodyStatus = "ACTIVE"
	ListAuctions200JSONResponseBodyStatusCANCELLED ListAuctions200JSONResponseBodyStatus = "CANCELLED"
	ListAuctions200JSONResponseBodyStatusCOMPLETED ListAuctions200JSONResponseBodyStatus = "COMPLETED"
)

// Valid indicates whether the value is a known member of the ListAuctions200JSONResponseBodyStatus enum.
func (e ListAuctions200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case ListAuctions200JSONResponseBodyStatusACTIVE:
		return true
	case ListAuctions200JSONResponseBodyStatusCANCELLED:
		return true
	case ListAuctions200JSONResponseBodyStatusCOMPLETED:
		return true
	default:
		return false
	}
}

// Defines values for CreateAuction201JSONResponseBodyItemRarity.
const (
	CreateAuction201JSONResponseBodyItemRarityCOMMON    CreateAuction201JSONResponseBodyItemRarity = "COMMON"
	CreateAuction201JSONResponseBodyItemRarityLEGENDARY CreateAuction201JSONResponseBodyItemRarity = "LEGENDARY"
	CreateAuction201JSONResponseBodyItemRarityRARE      CreateAuction201JSONResponseBodyItemRarity = "RARE"
)

// Valid indicates whether the value is a known member of the CreateAuction201JSONResponseBodyItemRarity enum.
func (e CreateAuction201JSONResponseBodyItemRarity) Valid() bool {
	switch e {
	case CreateAuction201JSONResponseBodyItemRarityCOMMON:
		return true
	case CreateAuction201JSONResponseBodyItemRarityLEGENDARY:
		return true
	case CreateAuction201JSONResponseBodyItemRarityRARE:
		return true
	default:
		return false
	}
}

// Defines values for CreateAuction201JSONResponseBodyStatus.
const (
	CreateAuction201JSONResponseBodyStatusACTIVE    CreateAuction201JSONResponseBodyStatus = "ACTIVE"
	CreateAuction201JSONResponseBodyStatusCANCELLED CreateAuction201JSONResponseBodyStatus = "CANCELLED"
	CreateAuction201JSONResponseBodyStatusCOMPLETED CreateAuction201JSONResponseBodyStatus = "COMPLETED"
)

// Valid indicates whether the value is a known member of the CreateAuction201JSONResponseBodyStatus enum.
func (e CreateAuction201JSONResponseBodyStatus) Valid() bool {
	switch e {
	case CreateAuction201JSONResponseBodyStatusACTIVE:
		return true
	case CreateAuction201JSONResponseBodyStatusCANCELLED:
		return true
	case CreateAuction201JSONResponseBodyStatusCOMPLETED:
		return true
	default:
		return false
	}
}

// Defines values for PlaceBid201JSONResponseBodyItemRarity.
const (
	PlaceBid201JSONResponseBodyItemRarityCOMMON    PlaceBid201JSONResponseBodyItemRarity = "COMMON"
	PlaceBid201JSONResponseBodyItemRarityLEGENDARY PlaceBid201JSONResponseBodyItemRarity = "LEGENDARY"
	PlaceBid201JSONResponseBodyItemRarityRARE      PlaceBid201JSONResponseBodyItemRarity = "RARE"
)

// Valid indicates whether the value is a known member of the PlaceBid201JSONResponseBodyItemRarity enum.
func (e PlaceBid201JSONResponseBodyItemRarity) Valid() bool {
	switch e {
	case PlaceBid201JSONResponseBodyItemRarityCOMMON:
		return true
	case PlaceBid201JSONResponseBodyItemRarityLEGENDARY:
		return true
	case PlaceBid201JSONResponseBodyItemRarityRARE:
		return true
	default:
		return false
	}
}

// Defines values for PlaceBid201JSONResponseBodyStatus.
const (
	PlaceBid201JSONResponseBodyStatusACTIVE    PlaceBid201JSONResponseBodyStatus = "ACTIVE"
	PlaceBid201JSONResponseBodyStatusCANCELLED PlaceBid201JSONResponseBodyStatus = "CANCELLED"
	PlaceBid201JSONResponseBodyStatusCOMPLETED PlaceBid201JSONResponseBodyStatus = "COMPLETED"
)

// Valid indicates whether the value is a known member of the PlaceBid201JSONResponseBodyStatus enum.
func (e PlaceBid201JSONResponseBodyStatus) Valid() bool {
	switch e {
	case PlaceBid201JSONResponseBodyStatusACTIVE:
		return true
	case PlaceBid201JSONResponseBodyStatusCANCELLED:
		return true
	case PlaceBid201JSONResponseBodyStatusCOMPLETED:
		return true
	default:
		return false
	}
}

// Defines values for ListInventory200JSONResponseBodyRarity.
const (
	ListInventory200JSONResponseBodyRarityCOMMON    ListInventory200JSONResponseBodyRarity = "COMMON"
	ListInventory200JSONResponseBodyRarityLEGENDARY ListInventory200JSONResponseBodyRarity = "LEGENDARY"
	ListInventory200JSONResponseBodyRarityRARE      ListInventory200JSONResponseBodyRarity = "RARE"
)

// Valid indicates whether the value is a known member of the ListInventory200JSONResponseBodyRarity enum.
func (e ListInventory200JSONResponseBodyRarity) Valid() bool {
	switch e {
	case ListInventory200JSONResponseBodyRarityCOMMON:
		return true
	case ListInventory200JSONResponseBodyRarityLEGENDARY:
		return true
	case ListInventory200JSONResponseBodyRarityRARE:
		return true
	default:
		return false
	}
}

// Defines values for ListListings200JSONResponseBodyItemRarity.
const (
	ListListings200JSONResponseBodyItemRarityCOMMON    ListListings200JSONResponseBodyItemRarity = "COMMON"
	ListListings200JSONResponseBodyItemRarityLEGENDARY ListListings200JSONResponseBodyItemRarity = "LEGENDARY"
	ListListings200JSONResponseBodyItemRarityRARE      ListListings200JSONResponseBodyItemRarity = "RARE"
)

// Valid indicates whether the value is a known member of the ListListings200JSONResponseBodyItemRarity enum.
func (e ListListings200JSONResponseBodyItemRarity) Valid() bool {
	switch e {
	case ListListings200JSONResponseBodyItemRarityCOMMON:
		return true
	case ListListings200JSONResponseBodyItemRarityLEGENDARY:
		return true
	case ListListings200JSONResponseBodyItemRarityRARE:
		return true
	default:
		return false
	}
}

// Defines values for ListListings200JSONResponseBodyStatus.
const (
	ListListings200JSONResponseBodyStatusACTIVE    ListListings200JSONResponseBodyStatus = "ACTIVE"
	ListListings200JSONResponseBodyStatusCANCELLED ListListings200JSONResponseBodyStatus = "CANCELLED"
	ListListings200JSONResponseBodyStatusSOLD      ListListings200JSONResponseBodyStatus = "SOLD"
)

// Valid indicates whether the value is a known member of the ListListings200JSONResponseBodyStatus enum.
func (e ListListings200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case ListListings200JSONResponseBodyStatusACTIVE:
		return true
	case ListListings200JSONResponseBodyStatusCANCELLED:
		return true
	case ListListings200JSONResponseBodyStatusSOLD:
		return true
	default:
		return false
	}
}

// Defines values for CreateListing201JSONResponseBodyItemRarity.
const (
	CreateListing201JSONResponseBodyItemRarityCOMMON    CreateListing201JSONResponseBodyItemRarity = "COMMON"
	CreateListing201JSONResponseBodyItemRarityLEGENDARY CreateListing201JSONResponseBodyItemRarity = "LEGENDARY"
	CreateListing201JSONResponseBodyItemRarityRARE      CreateListing201JSONResponseBodyItemRarity = "RARE"
)

// Valid indicates whether the value is a known member of the CreateListing201JSONResponseBodyItemRarity enum.
func (e CreateListing201JSONResponseBodyItemRarity) Valid() bool {
	switch e {
	case CreateListing201JSONResponseBodyItemRarityCOMMON:
		return true
	case CreateListing201JSONResponseBodyItemRarityLEGENDARY:
		return true
	case CreateListing201JSONResponseBodyItemRarityRARE:
		return true
	default:
		return false
	}
}

// Defines values for CreateListing201JSONResponseBodyStatus.
const (
	CreateListing201JSONResponseBodyStatusACTIVE    CreateListing201JSONResponseBodyStatus = "ACTIVE"
	CreateListing201JSONResponseBodyStatusCANCELLED CreateListing201JSONResponseBodyStatus = "CANCELLED"
	CreateListing201JSONResponseBodyStatusSOLD      CreateListing201JSONResponseBodyStatus = "SOLD"
)

// Valid indicates whether the value is a known member of the CreateListing201JSONResponseBodyStatus enum.
func (e CreateListing201JSONResponseBodyStatus) Valid() bool {
	switch e {
	case CreateListing201JSONResponseBodyStatusACTIVE:
		return true
	case CreateListing201JSONResponseBodyStatusCANCELLED:
		return true
	case CreateListing201JSONResponseBodyStatusSOLD:
		return true
	default:
		return false
	}
}

// Defines values for BuyListing200JSONResponseBodyItemRarity.
const (
	COMMON    BuyListing200JSONResponseBodyItemRarity = "COMMON"
	LEGENDARY BuyListing200JSONResponseBodyItemRarity = "LEGENDARY"
	RARE      BuyListing200JSONResponseBodyItemRarity = "RARE"
)

// Valid indicates whether the value is a known member of the BuyListing200JSONResponseBodyItemRarity enum.
func (e BuyListing200JSONResponseBodyItemRarity) Valid() bool {
	switch e {
	case COMMON:
		return true
	case LEGENDARY:
		return true
	case RARE:
		return true
	default:
		return false
	}
}

// Defines values for BuyListing200JSONResponseBodyStatus.
const (
	BuyListing200JSONResponseBodyStatusACTIVE    BuyListing200JSONResponseBodyStatus = "ACTIVE"
	BuyListing200JSONResponseBodyStatusCANCELLED BuyListing200JSONResponseBodyStatus = "CANCELLED"
	BuyListing200JSONResponseBodyStatusSOLD      BuyListing200JSONResponseBodyStatus = "SOLD"
)

// Valid indicates whether the value is a known member of the BuyListing200JSONResponseBodyStatus enum.
func (e BuyListing200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case BuyListing200JSONResponseBodyStatusACTIVE:
		return true
	case BuyListing200JSONResponseBodyStatusCANCELLED:
		return true
	case BuyListing200JSONResponseBodyStatusSOLD:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListAuctions200JSONResponseBodyItemRarity defines parameters for ListAuctions.
type ListAuctions200JSONResponseBodyItemRarity string

// ListAuctions200JSONResponseBodyStatus defines parameters for ListAuctions.
type ListAuctions200JSONResponseBodyStatus string

// CreateAuctionJSONBody defines parameters for CreateAuction.
type CreateAuctionJSONBody struct {
	// DurationSeconds Duration of the auction in seconds (1 min to 7 days)
	DurationSeconds int                `json:"duration_seconds"`
	ItemId          openapi_types.UUID `json:"item_id"`

	// StartPrice Starting bid price in copper coins
	StartPrice int `json:"start_price"`
}

// CreateAuction201JSONResponseBodyItemRarity defines parameters for CreateAuction.
type CreateAuction201JSONResponseBodyItemRarity string

// CreateAuction201JSONResponseBodyStatus defines parameters for CreateAuction.
type CreateAuction201JSONResponseBodyStatus string

// PlaceBidJSONBody defines parameters for PlaceBid.
type PlaceBidJSONBody struct {
	// Amount New bid amount in copper coins
	Amount int `json:"amount"`
}

// PlaceBid201JSONResponseBodyItemRarity defines parameters for PlaceBid.
type PlaceBid201JSONResponseBodyItemRarity string

// PlaceBid201JSONResponseBodyStatus defines parameters for PlaceBid.
type PlaceBid201JSONResponseBodyStatus string

// ListInventory200JSONResponseBodyRarity defines parameters for ListInventory.
type ListInventory200JSONResponseBodyRarity string

// ListListings200JSONResponseBodyItemRarity defines parameters for ListListings.
type ListListings200JSONResponseBodyItemRarity string

// ListListings200JSONResponseBodyStatus defines parameters for ListListings.
type ListListings200JSONResponseBodyStatus string

// CreateListingJSONBody defines parameters for CreateListing.
type CreateListingJSONBody struct {
	ItemId openapi_types.UUID `json:"item_id"`

	// Price Fixed price in copper coins
	Price int `json:"price"`
}

// CreateListing201JSONResponseBodyItemRarity defines parameters for CreateListing.
type CreateListing201JSONResponseBodyItemRarity string

// CreateListing201JSONResponseBodyStatus defines parameters for CreateListing.
type CreateListing201JSONResponseBodyStatus string

// BuyListing200JSONResponseBodyItemRarity defines parameters for BuyListing.
type BuyListing200JSONResponseBodyItemRarity string

// BuyListing200JSONResponseBodyStatus defines parameters for BuyListing.
type BuyListing200JSONResponseBodyStatus string

// DepositFundsJSONBody defines parameters for DepositFunds.
type DepositFundsJSONBody struct {
	// Amount The amount to deposit in copper coins (smallest currency unit)
	Amount int `json:"amount"`
}

// CreateAuctionJSONRequestBody defines body for CreateAuction for application/json ContentType.
type CreateAuctionJSONRequestBody CreateAuctionJSONBody

// PlaceBidJSONRequestBody defines body for PlaceBid for application/json ContentType.
type PlaceBidJSONRequestBody PlaceBidJSONBody

// CreateListingJSONRequestBody defines body for CreateListing for application/json ContentType.
type CreateListingJSONRequestBody CreateListingJSONBody

// DepositFundsJSONRequestBody defines body for DepositFunds for application/json ContentType.
type DepositFundsJSONRequestBody DepositFundsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List active auctions (Legendary items only)
	// (GET /auctions)
	ListAuctions(ctx echo.Context) error
	// List a Legendary item for auction
	// (POST /auctions)
	CreateAuction(ctx echo.Context) error
	// Place a bid on an active auction
	// (POST /auctions/{id}/bids)
	PlaceBid(ctx echo.Context, id openapi_types.UUID) error
	// List authenticated user's inventory
	// (GET /inventory)
	ListInventory(ctx echo.Context) error
	// List active marketplace listings (Common & Rare items)
	// (GET /marketplace/listings)
	ListListings(ctx echo.Context) error
	// Create a fixed-price listing
	// (POST /marketplace/listings)
	CreateListing(ctx echo.Context) error
	// Buy a listed item instantly
	// (POST /marketplace/listings/{id}/buy)
	BuyListing(ctx echo.Context, id openapi_types.UUID) error
	// Get wallet balance
	// (GET /wallet)
	GetWallet(ctx echo.Context) error
	// Deposit funds into wallet
	// (POST /wallet)
	DepositFunds(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListAuctions converts echo context to params.
func (w *ServerInterfaceWrapper) ListAuctions(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListAuctions(ctx)
	return err
}

// CreateAuction converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAuction(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAuction(ctx)
	return err
}

// PlaceBid converts echo context to params.
func (w *ServerInterfaceWrapper) PlaceBid(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PlaceBid(ctx, id)
	return err
}

// ListInventory converts echo context to params.
func (w *ServerInterfaceWrapper) ListInventory(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInventory(ctx)
	return err
}

// ListListings converts echo context to params.
func (w *ServerInterfaceWrapper) ListListings(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListListings(ctx)
	return err
}

// CreateListing converts echo context to params.
func (w *ServerInterfaceWrapper) CreateListing(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateListing(ctx)
	return err
}

// BuyListing converts echo context to params.
func (w *ServerInterfaceWrapper) BuyListing(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BuyListing(ctx, id)
	return err
}

// GetWallet converts echo context to params.
func (w *ServerInterfaceWrapper) GetWallet(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWallet(ctx)
	return err
}

// DepositFunds converts echo context to params.
func (w *ServerInterfaceWrapper) DepositFunds(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DepositFunds(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/auctions", wrapper.ListAuctions, options.OperationMiddlewares["listAuctions"]...)
	router.POST(options.BaseURL+"/auctions", wrapper.CreateAuction, options.OperationMiddlewares["createAuction"]...)
	router.POST(options.BaseURL+"/auctions/:id/bids", wrapper.PlaceBid, options.OperationMiddlewares["placeBid"]...)
	router.GET(options.BaseURL+"/inventory", wrapper.ListInventory, options.OperationMiddlewares["listInventory"]...)
	router.GET(options.BaseURL+"/marketplace/listings", wrapper.ListListings, options.OperationMiddlewares["listListings"]...)
	router.POST(options.BaseURL+"/marketplace/listings", wrapper.CreateListing, options.OperationMiddlewares["createListing"]...)
	router.POST(options.BaseURL+"/marketplace/listings/:id/buy", wrapper.BuyListing, options.OperationMiddlewares["buyListing"]...)
	router.GET(options.BaseURL+"/wallet", wrapper.GetWallet, options.OperationMiddlewares["getWallet"]...)
	router.POST(options.BaseURL+"/wallet", wrapper.DepositFunds, options.OperationMiddlewares["depositFunds"]...)

}

type ListAuctionsRequestObject struct {
}

type ListAuctionsResponseObject interface {
	VisitListAuctionsResponse(w http.ResponseWriter) error
}

type ListAuctions200JSONResponse []struct {
	AuctionId            openapi_types.UUID  `json:"auction_id"`
	CreatedAt            time.Time           `json:"created_at"`
	CurrentHighestBid    *int                `json:"current_highest_bid"`
	CurrentHighestBidder *openapi_types.UUID `json:"current_highest_bidder"`
	ExpiresAt            time.Time           `json:"expires_at"`
	Item                 struct {
		CreatedAt time.Time                                 `json:"created_at"`
		ItemId    openapi_types.UUID                        `json:"item_id"`
		Name      string                                    `json:"name"`
		OwnerId   openapi_types.UUID                        `json:"owner_id"`
		Rarity    ListAuctions200JSONResponseBodyItemRarity `json:"rarity"`
	} `json:"item"`
	SellerId   openapi_types.UUID                    `json:"seller_id"`
	StartPrice int                                   `json:"start_price"`
	Status     ListAuctions200JSONResponseBodyStatus `json:"status"`
}

func (response ListAuctions200JSONResponse) VisitListAuctionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuctions500JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response ListAuctions500JSONResponse) VisitListAuctionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuctionRequestObject struct {
	Body *CreateAuctionJSONRequestBody
}

type CreateAuctionResponseObject interface {
	VisitCreateAuctionResponse(w http.ResponseWriter) error
}

type CreateAuction201JSONResponse struct {
	AuctionId            openapi_types.UUID  `json:"auction_id"`
	CreatedAt            time.Time           `json:"created_at"`
	CurrentHighestBid    *int                `json:"current_highest_bid"`
	CurrentHighestBidder *openapi_types.UUID `json:"current_highest_bidder"`
	ExpiresAt            time.Time           `json:"expires_at"`
	Item                 struct {
		CreatedAt time.Time                                  `json:"created_at"`
		ItemId    openapi_types.UUID                         `json:"item_id"`
		Name      string                                     `json:"name"`
		OwnerId   openapi_types.UUID                         `json:"owner_id"`
		Rarity    CreateAuction201JSONResponseBodyItemRarity `json:"rarity"`
	} `json:"item"`
	SellerId   openapi_types.UUID                     `json:"seller_id"`
	StartPrice int                                    `json:"start_price"`
	Status     CreateAuction201JSONResponseBodyStatus `json:"status"`
}

func (response CreateAuction201JSONResponse) VisitCreateAuctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuction400JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response CreateAuction400JSONResponse) VisitCreateAuctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAuction401JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response CreateAuction401JSONResponse) VisitCreateAuctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlaceBidRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PlaceBidJSONRequestBody
}

type PlaceBidResponseObject interface {
	VisitPlaceBidResponse(w http.ResponseWriter) error
}

type PlaceBid201JSONResponse struct {
	AuctionId            openapi_types.UUID  `json:"auction_id"`
	CreatedAt            time.Time           `json:"created_at"`
	CurrentHighestBid    *int                `json:"current_highest_bid"`
	CurrentHighestBidder *openapi_types.UUID `json:"current_highest_bidder"`
	ExpiresAt            time.Time           `json:"expires_at"`
	Item                 struct {
		CreatedAt time.Time                             `json:"created_at"`
		ItemId    openapi_types.UUID                    `json:"item_id"`
		Name      string                                `json:"name"`
		OwnerId   openapi_types.UUID                    `json:"owner_id"`
		Rarity    PlaceBid201JSONResponseBodyItemRarity `json:"rarity"`
	} `json:"item"`
	SellerId   openapi_types.UUID                `json:"seller_id"`
	StartPrice int                               `json:"start_price"`
	Status     PlaceBid201JSONResponseBodyStatus `json:"status"`
}

func (response PlaceBid201JSONResponse) VisitPlaceBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PlaceBid400JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response PlaceBid400JSONResponse) VisitPlaceBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PlaceBid401JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response PlaceBid401JSONResponse) VisitPlaceBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListInventoryRequestObject struct {
}

type ListInventoryResponseObject interface {
	VisitListInventoryResponse(w http.ResponseWriter) error
}

type ListInventory200JSONResponse []struct {
	CreatedAt time.Time                              `json:"created_at"`
	ItemId    openapi_types.UUID                     `json:"item_id"`
	Name      string                                 `json:"name"`
	OwnerId   openapi_types.UUID                     `json:"owner_id"`
	Rarity    ListInventory200JSONResponseBodyRarity `json:"rarity"`
}

func (response ListInventory200JSONResponse) VisitListInventoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInventory401JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response ListInventory401JSONResponse) VisitListInventoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListInventory500JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response ListInventory500JSONResponse) VisitListInventoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListListingsRequestObject struct {
}

type ListListingsResponseObject interface {
	VisitListListingsResponse(w http.ResponseWriter) error
}

type ListListings200JSONResponse []struct {
	CreatedAt time.Time `json:"created_at"`
	Item      struct {
		CreatedAt time.Time                                 `json:"created_at"`
		ItemId    openapi_types.UUID                        `json:"item_id"`
		Name      string                                    `json:"name"`
		OwnerId   openapi_types.UUID                        `json:"owner_id"`
		Rarity    ListListings200JSONResponseBodyItemRarity `json:"rarity"`
	} `json:"item"`
	ListingId openapi_types.UUID                    `json:"listing_id"`
	Price     int                                   `json:"price"`
	SellerId  openapi_types.UUID                    `json:"seller_id"`
	Status    ListListings200JSONResponseBodyStatus `json:"status"`
}

func (response ListListings200JSONResponse) VisitListListingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListListings500JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response ListListings500JSONResponse) VisitListListingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateListingRequestObject struct {
	Body *CreateListingJSONRequestBody
}

type CreateListingResponseObject interface {
	VisitCreateListingResponse(w http.ResponseWriter) error
}

type CreateListing201JSONResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Item      struct {
		CreatedAt time.Time                                  `json:"created_at"`
		ItemId    openapi_types.UUID                         `json:"item_id"`
		Name      string                                     `json:"name"`
		OwnerId   openapi_types.UUID                         `json:"owner_id"`
		Rarity    CreateListing201JSONResponseBodyItemRarity `json:"rarity"`
	} `json:"item"`
	ListingId openapi_types.UUID                     `json:"listing_id"`
	Price     int                                    `json:"price"`
	SellerId  openapi_types.UUID                     `json:"seller_id"`
	Status    CreateListing201JSONResponseBodyStatus `json:"status"`
}

func (response CreateListing201JSONResponse) VisitCreateListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateListing400JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response CreateListing400JSONResponse) VisitCreateListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateListing401JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response CreateListing401JSONResponse) VisitCreateListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type BuyListingRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type BuyListingResponseObject interface {
	VisitBuyListingResponse(w http.ResponseWriter) error
}

type BuyListing200JSONResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Item      struct {
		CreatedAt time.Time                               `json:"created_at"`
		ItemId    openapi_types.UUID                      `json:"item_id"`
		Name      string                                  `json:"name"`
		OwnerId   openapi_types.UUID                      `json:"owner_id"`
		Rarity    BuyListing200JSONResponseBodyItemRarity `json:"rarity"`
	} `json:"item"`
	ListingId openapi_types.UUID                  `json:"listing_id"`
	Price     int                                 `json:"price"`
	SellerId  openapi_types.UUID                  `json:"seller_id"`
	Status    BuyListing200JSONResponseBodyStatus `json:"status"`
}

func (response BuyListing200JSONResponse) VisitBuyListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BuyListing400JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response BuyListing400JSONResponse) VisitBuyListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type BuyListing401JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response BuyListing401JSONResponse) VisitBuyListingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetWalletRequestObject struct {
}

type GetWalletResponseObject interface {
	VisitGetWalletResponse(w http.ResponseWriter) error
}

type GetWallet200JSONResponse struct {
	// AvailableBalance Funds available for bidding or purchasing
	AvailableBalance int    `json:"available_balance"`
	Currency         string `json:"currency"`

	// ReservedBalance Funds currently held/locked in active bids
	ReservedBalance int `json:"reserved_balance"`

	// TotalBalance Total funds (available + reserved)
	TotalBalance int                `json:"total_balance"`
	UserId       openapi_types.UUID `json:"user_id"`
	WalletId     openapi_types.UUID `json:"wallet_id"`
}

func (response GetWallet200JSONResponse) VisitGetWalletResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWallet401JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response GetWallet401JSONResponse) VisitGetWalletResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetWallet500JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response GetWallet500JSONResponse) VisitGetWalletResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DepositFundsRequestObject struct {
	Body *DepositFundsJSONRequestBody
}

type DepositFundsResponseObject interface {
	VisitDepositFundsResponse(w http.ResponseWriter) error
}

type DepositFunds200JSONResponse struct {
	// AvailableBalance Funds available for bidding or purchasing
	AvailableBalance int    `json:"available_balance"`
	Currency         string `json:"currency"`

	// ReservedBalance Funds currently held/locked in active bids
	ReservedBalance int `json:"reserved_balance"`

	// TotalBalance Total funds (available + reserved)
	TotalBalance int                `json:"total_balance"`
	UserId       openapi_types.UUID `json:"user_id"`
	WalletId     openapi_types.UUID `json:"wallet_id"`
}

func (response DepositFunds200JSONResponse) VisitDepositFundsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DepositFunds400JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response DepositFunds400JSONResponse) VisitDepositFundsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DepositFunds401JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response DepositFunds401JSONResponse) VisitDepositFundsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List active auctions (Legendary items only)
	// (GET /auctions)
	ListAuctions(ctx context.Context, request ListAuctionsRequestObject) (ListAuctionsResponseObject, error)
	// List a Legendary item for auction
	// (POST /auctions)
	CreateAuction(ctx context.Context, request CreateAuctionRequestObject) (CreateAuctionResponseObject, error)
	// Place a bid on an active auction
	// (POST /auctions/{id}/bids)
	PlaceBid(ctx context.Context, request PlaceBidRequestObject) (PlaceBidResponseObject, error)
	// List authenticated user's inventory
	// (GET /inventory)
	ListInventory(ctx context.Context, request ListInventoryRequestObject) (ListInventoryResponseObject, error)
	// List active marketplace listings (Common & Rare items)
	// (GET /marketplace/listings)
	ListListings(ctx context.Context, request ListListingsRequestObject) (ListListingsResponseObject, error)
	// Create a fixed-price listing
	// (POST /marketplace/listings)
	CreateListing(ctx context.Context, request CreateListingRequestObject) (CreateListingResponseObject, error)
	// Buy a listed item instantly
	// (POST /marketplace/listings/{id}/buy)
	BuyListing(ctx context.Context, request BuyListingRequestObject) (BuyListingResponseObject, error)
	// Get wallet balance
	// (GET /wallet)
	GetWallet(ctx context.Context, request GetWalletRequestObject) (GetWalletResponseObject, error)
	// Deposit funds into wallet
	// (POST /wallet)
	DepositFunds(ctx context.Context, request DepositFundsRequestObject) (DepositFundsResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListAuctions operation middleware
func (sh *strictHandler) ListAuctions(ctx echo.Context) error {
	var request ListAuctionsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuctions(ctx.Request().Context(), request.(ListAuctionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuctions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListAuctionsResponseObject); ok {
		return validResponse.VisitListAuctionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateAuction operation middleware
func (sh *strictHandler) CreateAuction(ctx echo.Context) error {
	var request CreateAuctionRequestObject

	var body CreateAuctionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAuction(ctx.Request().Context(), request.(CreateAuctionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAuction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateAuctionResponseObject); ok {
		return validResponse.VisitCreateAuctionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PlaceBid operation middleware
func (sh *strictHandler) PlaceBid(ctx echo.Context, id openapi_types.UUID) error {
	var request PlaceBidRequestObject

	request.Id = id

	var body PlaceBidJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PlaceBid(ctx.Request().Context(), request.(PlaceBidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlaceBid")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PlaceBidResponseObject); ok {
		return validResponse.VisitPlaceBidResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListInventory operation middleware
func (sh *strictHandler) ListInventory(ctx echo.Context) error {
	var request ListInventoryRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListInventory(ctx.Request().Context(), request.(ListInventoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInventory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListInventoryResponseObject); ok {
		return validResponse.VisitListInventoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListListings operation middleware
func (sh *strictHandler) ListListings(ctx echo.Context) error {
	var request ListListingsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListListings(ctx.Request().Context(), request.(ListListingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListListings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListListingsResponseObject); ok {
		return validResponse.VisitListListingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateListing operation middleware
func (sh *strictHandler) CreateListing(ctx echo.Context) error {
	var request CreateListingRequestObject

	var body CreateListingJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateListing(ctx.Request().Context(), request.(CreateListingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateListing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateListingResponseObject); ok {
		return validResponse.VisitCreateListingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// BuyListing operation middleware
func (sh *strictHandler) BuyListing(ctx echo.Context, id openapi_types.UUID) error {
	var request BuyListingRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.BuyListing(ctx.Request().Context(), request.(BuyListingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BuyListing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(BuyListingResponseObject); ok {
		return validResponse.VisitBuyListingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetWallet operation middleware
func (sh *strictHandler) GetWallet(ctx echo.Context) error {
	var request GetWalletRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWallet(ctx.Request().Context(), request.(GetWalletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWallet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWalletResponseObject); ok {
		return validResponse.VisitGetWalletResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DepositFunds operation middleware
func (sh *strictHandler) DepositFunds(ctx echo.Context) error {
	var request DepositFundsRequestObject

	var body DepositFundsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DepositFunds(ctx.Request().Context(), request.(DepositFundsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DepositFunds")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DepositFundsResponseObject); ok {
		return validResponse.VisitDepositFundsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fprb9u8Ff4rBDdgKSbHsttc4G+5Fh7SJEjSvdjawqDFY5tvKVIjKSdekf8+8CLZkuUkTpvEBdYPRSxT",
	"1Lk8zzkPj/wDJzLNpABhNO79wDqZQErcn/MvBuHqgChFZnpwkCeGSdE3kLqVrPjjrwpGuIf/0p7f2w73",
	"thu2U6AzKTSUO16FC/g+wmaWAe5h90j7ebU5fTEFYaSa/UKD7FbPs+aMacPE+BfaEnZc0xwF/8lBGz04",
	"UkAMlBF2V609mZIZKMPAWUdzReyCgYZECuqvgU4Uy+xl3MPHYQWSI2QmgIjfETGBwj1oq4NSJpCRaA9R",
	"MtPvcIThjqQZB9zb3/0QxxFOyR1L8xT3duMP++4CE8WF0jEmDIxBWdds/AaMWnvKrXDc2Yf3pDtqdbrv",
	"P7T24jhu7dv/4uJfJ+7gCI+kSonBPZznjOJyd20UE2O7uTZEmUGmWALLDl/bL5kYoyGjyK2xviYyy0Ch",
	"RDKhF93bsY9d8Kaz7Mx9hG1WmAKKe19Kz6pmRMup+FZuJYd/QmKelvESNisy/qKBXRHSU3YHT4hlZ+f5",
	"sfRPXjdkx5BJzczKYJFU5sIsO3RjieC+s6infpe6a2hLp4Rz0AYluVIgkhnKBTMVenTWxk+waV1XLzlJ",
	"4JDRtX09h1tHheDvQ1zYeWlfVjWOZWf8gvWB/v5pQE8c1+iAmOr+3bi724r3Wp3dm85er7PTi+N/L+5H",
	"iYGWYSk0bupQYgYTNp6ANoNhzfoQX5FzTob2glE5NBXPho0oqDUjEcfdhkisePjcCbjLmAK9OjJ7z4iM",
	"5fkvbewaOAe1Pjzi+P0zGky9WyxnTBticodcEJY6X/DB0U3/nyc4wkcXny7PTm5Oju3fB+dHJ2dnJ8eW",
	"MnOzy7U1Q+psm5MihHQxEM34WwmmevsKHlQAUOHJ2iQ/UUqqZWonklaDivvn159PT/tH/ZPzm8Hp5/Pj",
	"66acpKA1Gddu/cMWaIOGhBNhm5NGRkrE5a2t6wo0qCmgUEOBolFuG/NjcXYWzh+4tuMVsC77/xKl50VV",
	"gSBpLezHioylaF0nhAO6njDgjTfKW/E8knafYpYiipnZIueOLj59ujjHEb46uLJ0Ojv5eHJ+fHD1ryrd",
	"5pcfQ8Jcn5SuhHCUj/85jtQPCa+Hll9ajrl3Y/1Ud9fUpXWt2VCJX7wzrCr01xdnP1/jFyLZWOOXyvXP",
	"oM9XzwdU2JQwpxYGocA2HA1sRUXlQjSSyqpNag9gUqEsV8mEaOtp9IQ2Wujsau4++sAuFwBf3+lj1oUO",
	"yGdoApy2uUy+A7VCmCSGTcHaW9HB3VXYMtIQvvppN/Zr32PQ1jwkfy8aEa2cHPZWPSXXL1g0b13Kn7P9",
	"E4haw/L8WXOnogZQNWSyHusFaCyj3LE+yW05vrYY9+A9BKJAHeRmYj8N3afTwv5//HFjSeRW4174du7Q",
	"xJgM39uNmRjJ5UxfKkm9GGuNFaEQoUQKo0hiWiOmtEEHl31HBTMB5Jsl+kTUdzCZPcZtfxXHMGICNLKh",
	"SwwaylxQohhoNARzCyCQJ2eEyjlZtLhFhIigKJyjUCppzkFvfxXWB2YWmvTiTdYsHOEpKO396GzH27Hr",
	"1BkIkjHcw++3421bCTNiJi6O7SA73YcxuD5ki4QbdvSp7adMm4NikUumry92ZTeOvegTBvzplGQZZ4m7",
	"u/2ntmYU88tntKSm0abLW20mlCcJaD3KeTH/0kiBUQymhFv/d17WzLoobjLREkAhCN9HWOdpStQsxLeo",
	"VaX5W2cwBouZGXKzSiQFn71zzVLqhiRV5onYExW0OZR09rKePzTPvK+WDHskvV8CUOd1MrM0zF7OUUG3",
	"0HORLmHF3Tz3w5ujqC+mhDNaHHlsC7boQF6soq001wYNAZXgeeft7ryx3Z8Fyc1EKvZfoI3oR1W4u+Ia",
	"uODWl1Wq/YPR+7Zr6VbPNHKhmKW5MqdICgaUxr0vPzCzxtjSV+j8HnbLqhiNFmLxWEv89vpUq48KfzOW",
	"HTKKXLuqEixCmYIpk7lGfoQRlJYCkysBNEICbstrXk9sBikvcjNkNCpfvfgJC42QBj5qBbUcOa4KnY9G",
	"LGEgTBhWbDo9HdgQcSNmKRARtU7l2ckKEfOgiCilztuoiNobyYd1RJAPgOQIWXGL5i5uYMp+C4WTmwkI",
	"Y00C6mL6N70YVYujdC5m2+Go/LAuPSsWvQmiKm+VH8aT9eY31aQLSUFFUtDWkUxTKdDXPI67u+iKKPBC",
	"9VGNGoL2Zhq19gZ2k7rn0m8KlnMWlhQadTNlaUZmXBJal6dWO6GthAghjSfEXPVNQMHmi1WPIETQiN0B",
	"bflX5oETqytY0Kz5bLVkPcxnc168jmh9vWq5FsAv/UgRkN2Iw4aewyyqteQ0QgkRCXBu9V5d4d1W3l5t",
	"PLgP8xkiDs1APW+Z0IYIw0N39v6s7McfwfihFn4reNUG3g935JAdLuX3PPu/qFtbInyEJoQ3l7fwQ57T",
	"8H72tRt/7XdET2r5GwPZYPxCFdzopr/xZa6Ipx8lMGFkgLHfp3jV4Frv4kuGL99s33SDh9CYa8pMJoSj",
	"Y5gCl1lq678nD45wrnh469Brt7ldN5Ha9Pbj/bhNMtaedvD9t/v/BQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
